default_env: QA
default_client: YATRA
default_workspace: Reserve bank of india yatra  # fallback workspace if none passed from CLI

environments:
  QA:
    clients:
      YATRA:
        url: "https://myyatra.finkraft.ai/auth/signin"
        username: ${QA_YATRA_USERNAME}
        password: ${QA_YATRA_PASSWORD}
        workspaces:
          - Reserve bank of india yatra
          - workspace2
        expected_top_modules:
          - Dashboard - Airline
          - Dashboard - Hotel
      client2:
        url: "https://client2.qa.example.com"
        username: "user2"
        password: "pass2"
        workspaces:
          - workspaceA
          - workspaceB
