name: Test Automation Framework CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.9'

jobs:
  test:
    name: CLI Pytest + Allure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xzf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Run pytest with CLI args & Allure output
        run: |
          pytest src/tests/ \
            --client=MMT \
            --workspace="Kotak securities" \
            --headless=true \
            --maxfail=1 \
            --self-contained-html
        env:
          QA_YATRA_USERNAME: ${{ secrets.QA_YATRA_USERNAME }}
          QA_YATRA_PASSWORD: ${{ secrets.QA_YATRA_PASSWORD }}

      - name: Generate Allure report
        if: always()
        run: |
          allure generate --clean --output reports/allure-report reports/allure-results

      - name: Upload Allure report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report/

      - name: Upload Pytest HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: reports/html/report.html
